language: php

sudo: false

php: [5.6, 7.0, 7.1, 7.2, 7.3, 7.4, 8.0snapshot]

matrix:
  include:
    - php: 5.4
      dist: trusty
    - php: 5.5
      dist: trusty
    - php: 5.3
      dist: precise
    # Test against LTS versions
    - php: 7.2
      env: SYMFONY_VERSION='^2'
    - php: 7.2
      env: SYMFONY_VERSION='^3'
    # Test against dev versions of dependencies
    - php: 7.2
      env: DEPENDENCIES='dev'

cache:
  directories:
    - $HOME/.composer/cache/files

before_install:
  - if [ "$DEPENDENCIES" = "dev" ]; then composer config minimum-stability dev; fi;
  # Install symfony/error-handler on compatible PHP versions to avoid a deprecation warning of the old DebugClassLoader and ErrorHandler classes
  - if [[ "$TRAVIS_PHP_VERSION" != 5.* && "$TRAVIS_PHP_VERSION" != 7.0 && "$SYMFONY_VERSION" = "" ]]; then composer require --no-update --dev symfony/error-handler "^4.4 || ^5.0"; fi;
  - sh -c 'if [ "$SYMFONY_VERSION" != "" ]; then composer require -n --no-update symfony/lts=$SYMFONY_VERSION; fi;'
  - if (( "${TRAVIS_PHP_VERSION:0:1}" >= "8" )) ; then composer require --dev --no-update  "phpunit/phpunit:^7.5.18"; fi;

install:
  -  if (( "${TRAVIS_PHP_VERSION:3}" == "snapshot" )) ; then composer install --ignore-platform-req=php -n --prefer-dist; else  composer install  -n --prefer-dist; fi;

script: |
  #!/usr/bin/env bash
  set -e
  if (( "${TRAVIS_PHP_VERSION:0:1}" >= "8" )) ; then
    # In php 8.0+ we have Xdebug 3.0+ and phpunit:^7.5.18 will throw RuntimeException in vendor/phpunit/php-code-coverage/src/Driver/Xdebug.php:42
    # because option xdebug.coverage_enable does not exists in XDebug 3.0+.
    # More info is at https://3.xdebug.org/docs/upgrade_guide
    vendor/bin/phpunit -v
  else
    vendor/bin/phpunit -v --coverage-clover=coverage.clover
  fi

after_script:
  - |
    #!/usr/bin/env bash
    set -e

    if [[ -f "coverage.clover" ]]; then
      wget https://scrutinizer-ci.com/ocular.phar
      php ocular.phar code-coverage:upload --format=php-clover coverage.clover
    fi
